import 'dotenv/config';
import mongoose from 'mongoose';
import Exercise from '../models/Exercise';

const EXERCISES = [
  // ========================
  // YOGA (25 bài)
  // ========================
  {
    name: 'Tư thế ngọn núi',
    nameEn: 'Mountain Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Tư thế đứng cơ bản giúp cải thiện tư thế và tập trung tâm trí.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, hai chân chụm lại, trọng lượng phân đều hai bàn chân.', durationSeconds: 10 },
      { order: 2, instruction: 'Kéo dài cột sống, vai thả lỏng và hạ xuống.', durationSeconds: 10 },
      { order: 3, instruction: 'Hít thở sâu và giữ tư thế trong 30 giây đến 1 phút.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế chiến binh I',
    nameEn: 'Warrior I',
    category: 'yoga',
    difficulty: 'medium',
    durationMinutes: 8,
    caloriesBurned: 50,
    imageUrl: null,
    description: 'Tư thế tăng cường sức mạnh chân và mở rộng ngực.',
    steps: [
      { order: 1, instruction: 'Bước chân phải về phía trước khoảng 1 mét, khuỵu gối phải 90 độ.', durationSeconds: 10 },
      { order: 2, instruction: 'Chân trái duỗi thẳng, gót chân ép xuống sàn.', durationSeconds: 10 },
      { order: 3, instruction: 'Giơ hai tay lên cao, lòng bàn tay hướng vào nhau.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ tư thế 30 giây rồi đổi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế chiến binh II',
    nameEn: 'Warrior II',
    category: 'yoga',
    difficulty: 'medium',
    durationMinutes: 8,
    caloriesBurned: 55,
    imageUrl: null,
    description: 'Tư thế tăng cường sức bền và mở hông.',
    steps: [
      { order: 1, instruction: 'Dang rộng hai chân khoảng 1,2 mét, bàn chân phải xoay 90 độ ra ngoài.', durationSeconds: 10 },
      { order: 2, instruction: 'Khuỵu gối phải 90 độ, gối thẳng với mắt cá chân.', durationSeconds: 10 },
      { order: 3, instruction: 'Giơ hai tay ngang vai, mắt nhìn về phía tay phải.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ tư thế 30 giây rồi đổi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế tam giác',
    nameEn: 'Triangle Pose',
    category: 'yoga',
    difficulty: 'medium',
    durationMinutes: 7,
    caloriesBurned: 45,
    imageUrl: null,
    description: 'Tư thế kéo giãn hông và cột sống, tăng cường thăng bằng.',
    steps: [
      { order: 1, instruction: 'Dang hai chân rộng, bàn chân phải xoay 90 độ ra ngoài.', durationSeconds: 10 },
      { order: 2, instruction: 'Duỗi thẳng tay phải về phía chân phải, hạ xuống chạm ống chân hoặc sàn.', durationSeconds: 15 },
      { order: 3, instruction: 'Tay trái giơ thẳng lên trần nhà, mắt nhìn lên tay trái.', durationSeconds: 15 },
      { order: 4, instruction: 'Giữ 30 giây rồi đổi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế cây',
    nameEn: 'Tree Pose',
    category: 'yoga',
    difficulty: 'medium',
    durationMinutes: 6,
    caloriesBurned: 35,
    imageUrl: null,
    description: 'Tư thế cân bằng giúp cải thiện tập trung và sức mạnh một chân.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng trên chân trái, đặt bàn chân phải lên đùi trái.', durationSeconds: 10 },
      { order: 2, instruction: 'Chắp tay trước ngực hoặc giơ tay lên cao.', durationSeconds: 10 },
      { order: 3, instruction: 'Tập trung mắt vào một điểm cố định, giữ 30-60 giây.', durationSeconds: 45 },
      { order: 4, instruction: 'Đổi chân và lặp lại.', durationSeconds: 45 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế chó úp mặt',
    nameEn: 'Downward Dog',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 40,
    imageUrl: null,
    description: 'Tư thế kéo giãn toàn thân, tăng cường sức mạnh tay và vai.',
    steps: [
      { order: 1, instruction: 'Bắt đầu ở tư thế bốn điểm chống (tay và gối).', durationSeconds: 5 },
      { order: 2, instruction: 'Nâng hông lên cao tạo hình chữ V ngược, duỗi thẳng chân.', durationSeconds: 15 },
      { order: 3, instruction: 'Ép gót chân xuống sàn, đầu thả lỏng giữa hai tay.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ tư thế 1-2 phút, hít thở đều.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế em bé',
    nameEn: 'Child\'s Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Tư thế thư giãn nhẹ nhàng, kéo giãn lưng và hông.',
    steps: [
      { order: 1, instruction: 'Quỳ gối, ngồi xuống gót chân.', durationSeconds: 5 },
      { order: 2, instruction: 'Cúi người về phía trước, tay duỗi thẳng phía trước mặt.', durationSeconds: 10 },
      { order: 3, instruction: 'Trán chạm sàn, vai thả lỏng.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ tư thế 1-3 phút, hít thở sâu.', durationSeconds: 90 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế rắn hổ mang',
    nameEn: 'Cobra Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 35,
    imageUrl: null,
    description: 'Tư thế mở ngực và tăng cường cột sống lưng.',
    steps: [
      { order: 1, instruction: 'Nằm sấp, hai tay đặt dưới vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Nâng ngực lên khỏi sàn bằng cách đẩy tay, khuỷu tay hơi cong.', durationSeconds: 15 },
      { order: 3, instruction: 'Vai kéo về phía sau và xuống, không nhún vai lên tai.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ 15-30 giây, lặp lại 3 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế cây cầu',
    nameEn: 'Bridge Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 7,
    caloriesBurned: 45,
    imageUrl: null,
    description: 'Tăng cường cơ mông, lưng dưới và kéo giãn ngực.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, khuỵu gối, bàn chân đặt phẳng trên sàn gần mông.', durationSeconds: 5 },
      { order: 2, instruction: 'Ép hai tay và bàn chân xuống sàn, nâng hông lên.', durationSeconds: 15 },
      { order: 3, instruction: 'Giữ vai trên sàn, siết cơ mông.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ 30 giây, hạ xuống, lặp lại 3 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế thiền ngồi',
    nameEn: 'Seated Meditation',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 10,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Thiền ngồi giúp giảm căng thẳng và cải thiện tập trung.',
    steps: [
      { order: 1, instruction: 'Ngồi bắt chéo chân trên sàn hoặc trên đệm thiền.', durationSeconds: 10 },
      { order: 2, instruction: 'Đặt tay lên đùi, lưng thẳng, vai thả lỏng.', durationSeconds: 10 },
      { order: 3, instruction: 'Nhắm mắt, hít thở sâu và chú ý vào hơi thở.', durationSeconds: 300 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế gập người về trước',
    nameEn: 'Standing Forward Bend',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 35,
    imageUrl: null,
    description: 'Kéo giãn gân kheo, lưng dưới và giải phóng căng thẳng.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, hai chân rộng bằng vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Hít vào sâu, thở ra cúi người về phía trước từ khớp hông.', durationSeconds: 15 },
      { order: 3, instruction: 'Thả hai tay xuống chạm sàn hoặc nắm lấy ống chân.', durationSeconds: 15 },
      { order: 4, instruction: 'Giữ 30-60 giây, hít thở đều.', durationSeconds: 45 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế ngồi gập về trước',
    nameEn: 'Seated Forward Bend',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 6,
    caloriesBurned: 35,
    imageUrl: null,
    description: 'Kéo giãn gân kheo và lưng dưới, thư giãn hệ thần kinh.',
    steps: [
      { order: 1, instruction: 'Ngồi duỗi thẳng hai chân trên sàn, lưng thẳng.', durationSeconds: 5 },
      { order: 2, instruction: 'Hít vào, giơ tay lên cao, thở ra cúi người về phía trước.', durationSeconds: 15 },
      { order: 3, instruction: 'Cố gắng chạm ngón tay vào bàn chân hoặc ống chân.', durationSeconds: 15 },
      { order: 4, instruction: 'Giữ 30-60 giây, thở đều.', durationSeconds: 45 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế xoay cột sống ngồi',
    nameEn: 'Seated Spinal Twist',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 6,
    caloriesBurned: 32,
    imageUrl: null,
    description: 'Xoay cột sống giúp giải độc và cải thiện tiêu hóa.',
    steps: [
      { order: 1, instruction: 'Ngồi duỗi thẳng hai chân, co chân phải, đặt bàn chân ngoài đùi trái.', durationSeconds: 10 },
      { order: 2, instruction: 'Đặt tay trái ra sau lưng, tay phải giữ đầu gối trái.', durationSeconds: 10 },
      { order: 3, instruction: 'Xoay thân người sang phải, nhìn qua vai phải.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30 giây, đổi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế bướm',
    nameEn: 'Butterfly Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 7,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Kéo giãn cơ đùi trong và khớp hông.',
    steps: [
      { order: 1, instruction: 'Ngồi, chắp lòng bàn chân lại với nhau, kéo gót chân về gần cơ thể.', durationSeconds: 10 },
      { order: 2, instruction: 'Giữ bàn chân bằng hai tay, lưng thẳng.', durationSeconds: 10 },
      { order: 3, instruction: 'Nhẹ nhàng ép đầu gối xuống sàn như cánh bướm.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 1-2 phút, hít thở đều.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế pigeon (bồ câu)',
    nameEn: 'Pigeon Pose',
    category: 'yoga',
    difficulty: 'hard',
    durationMinutes: 10,
    caloriesBurned: 60,
    imageUrl: null,
    description: 'Kéo giãn sâu cơ hông và đùi, giải phóng căng thẳng tích tụ.',
    steps: [
      { order: 1, instruction: 'Từ tư thế chó úp mặt, đưa chân phải ra phía trước, đầu gối hướng ra ngoài.', durationSeconds: 15 },
      { order: 2, instruction: 'Chân trái duỗi thẳng ra phía sau, hông song song với sàn.', durationSeconds: 15 },
      { order: 3, instruction: 'Cúi người về phía trước, tay duỗi thẳng, trán chạm sàn.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 1 phút rồi đổi bên.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế mặt trăng lưỡi liềm',
    nameEn: 'Crescent Lunge',
    category: 'yoga',
    difficulty: 'medium',
    durationMinutes: 8,
    caloriesBurned: 50,
    imageUrl: null,
    description: 'Tăng cường đùi, mở hông và kéo giãn cơ gấp hông.',
    steps: [
      { order: 1, instruction: 'Bước chân phải lên phía trước, khuỵu gối 90 độ.', durationSeconds: 10 },
      { order: 2, instruction: 'Hạ gối trái gần chạm sàn, duỗi thẳng chân trái ra sau.', durationSeconds: 10 },
      { order: 3, instruction: 'Nâng tay lên cao, nhìn lên trên, mở rộng ngực.', durationSeconds: 15 },
      { order: 4, instruction: 'Giữ 30 giây rồi đổi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế bàn chân sau đầu',
    nameEn: 'Happy Baby Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 28,
    imageUrl: null,
    description: 'Kéo giãn cơ đùi trong và lưng dưới, thư giãn hoàn toàn.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, co gối lên bụng.', durationSeconds: 5 },
      { order: 2, instruction: 'Nắm lấy lòng bàn chân, kéo đầu gối về phía nách.', durationSeconds: 15 },
      { order: 3, instruction: 'Giữ gót chân thẳng trên đầu gối, lưng phẳng trên sàn.', durationSeconds: 15 },
      { order: 4, instruction: 'Lắc nhẹ hai bên, giữ 1-2 phút.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế chiến binh III',
    nameEn: 'Warrior III',
    category: 'yoga',
    difficulty: 'hard',
    durationMinutes: 10,
    caloriesBurned: 65,
    imageUrl: null,
    description: 'Tăng cường sức mạnh toàn thân và thăng bằng nâng cao.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng trên chân phải, nghiêng người về phía trước.', durationSeconds: 10 },
      { order: 2, instruction: 'Nâng chân trái lên ngang với hông, tạo đường thẳng từ đầu đến gót chân.', durationSeconds: 15 },
      { order: 3, instruction: 'Tay duỗi thẳng về phía trước hoặc ngang hông.', durationSeconds: 15 },
      { order: 4, instruction: 'Giữ 20-30 giây rồi đổi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế ghế ngồi',
    nameEn: 'Chair Pose',
    category: 'yoga',
    difficulty: 'medium',
    durationMinutes: 7,
    caloriesBurned: 55,
    imageUrl: null,
    description: 'Tăng cường đùi và mông, cải thiện tư thế tổng thể.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, hai chân chụm lại.', durationSeconds: 5 },
      { order: 2, instruction: 'Khuỵu gối như ngồi trên ghế vô hình, đùi song song với sàn.', durationSeconds: 15 },
      { order: 3, instruction: 'Giơ tay lên cao, vai thả lỏng, nhìn thẳng.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ 30 giây, thực hiện 3-5 hiệp.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế đầu gối đến ngực',
    nameEn: 'Knees to Chest Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 28,
    imageUrl: null,
    description: 'Giảm đau lưng dưới và xoa bóp vùng bụng nhẹ nhàng.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, co hai chân lên ngực.', durationSeconds: 10 },
      { order: 2, instruction: 'Ôm hai đầu gối vào ngực, nâng đầu lên gần gối.', durationSeconds: 15 },
      { order: 3, instruction: 'Lắc nhẹ sang hai bên để xoa lưng.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 1 phút, hít thở đều.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế xác chết',
    nameEn: 'Corpse Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 10,
    caloriesBurned: 25,
    imageUrl: null,
    description: 'Thư giãn hoàn toàn cơ thể và tâm trí sau khi luyện tập.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa thoải mái, hai tay xuôi theo thân, lòng bàn tay ngửa lên.', durationSeconds: 10 },
      { order: 2, instruction: 'Nhắm mắt, thả lỏng toàn thân từ ngón chân đến đỉnh đầu.', durationSeconds: 30 },
      { order: 3, instruction: 'Hít thở tự nhiên, không cố gắng kiểm soát hơi thở.', durationSeconds: 300 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế mèo bò',
    nameEn: 'Cat-Cow Pose',
    category: 'yoga',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 32,
    imageUrl: null,
    description: 'Tăng cường linh hoạt cột sống và giảm căng thẳng lưng.',
    steps: [
      { order: 1, instruction: 'Bắt đầu ở tư thế bốn điểm chống (tay thẳng dưới vai, gối dưới hông).', durationSeconds: 5 },
      { order: 2, instruction: 'Hít vào: cong lưng xuống (bò), ngẩng đầu và mông lên (tư thế bò).', durationSeconds: 10 },
      { order: 3, instruction: 'Thở ra: cong lưng lên (mèo), cúi đầu và thu mông vào (tư thế mèo).', durationSeconds: 10 },
      { order: 4, instruction: 'Lặp lại nhịp nhàng 10-15 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế chim công',
    nameEn: 'Crow Pose',
    category: 'yoga',
    difficulty: 'hard',
    durationMinutes: 12,
    caloriesBurned: 70,
    imageUrl: null,
    description: 'Tư thế thăng bằng tay nâng cao, tăng sức mạnh tay và lõi.',
    steps: [
      { order: 1, instruction: 'Ngồi xổm, hai tay đặt trên sàn rộng bằng vai.', durationSeconds: 10 },
      { order: 2, instruction: 'Đặt đầu gối vào bắp tay trên, nghiêng người về phía trước.', durationSeconds: 15 },
      { order: 3, instruction: 'Chuyển trọng lượng lên tay, nhấc hai chân khỏi sàn.', durationSeconds: 20 },
      { order: 4, instruction: 'Giữ thăng bằng 5-15 giây, tập nhiều lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế cá',
    nameEn: 'Fish Pose',
    category: 'yoga',
    difficulty: 'medium',
    durationMinutes: 6,
    caloriesBurned: 40,
    imageUrl: null,
    description: 'Mở rộng lồng ngực, kéo giãn cổ và tăng cường hô hấp.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, tay đặt dưới mông, lòng bàn tay úp xuống.', durationSeconds: 10 },
      { order: 2, instruction: 'Nâng ngực lên, cúi đầu về phía sau chạm đỉnh đầu xuống sàn.', durationSeconds: 15 },
      { order: 3, instruction: 'Duy trì trọng lượng chính trên tay và khuỷu tay, không ép cổ.', durationSeconds: 10 },
      { order: 4, instruction: 'Giữ 15-30 giây, thở sâu mở rộng lồng ngực.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế đứng gập lưng',
    nameEn: 'Wheel Pose',
    category: 'yoga',
    difficulty: 'hard',
    durationMinutes: 12,
    caloriesBurned: 75,
    imageUrl: null,
    description: 'Tư thế nâng cao mở rộng toàn bộ phần trước cơ thể.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, đặt tay cạnh tai lòng bàn tay úp xuống, khuỵu gối.', durationSeconds: 10 },
      { order: 2, instruction: 'Ép tay và chân xuống sàn, nâng hông và ngực lên cao.', durationSeconds: 20 },
      { order: 3, instruction: 'Duỗi thẳng tay, đỉnh đầu có thể chạm sàn nhẹ hoặc không.', durationSeconds: 15 },
      { order: 4, instruction: 'Giữ 10-20 giây, hạ xuống từ từ. Lặp 3 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },

  // ========================
  // CARDIO (25 bài)
  // ========================
  {
    name: 'Chạy bộ tại chỗ',
    nameEn: 'Jogging in Place',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 10,
    caloriesBurned: 80,
    imageUrl: null,
    description: 'Bài tập cardio đơn giản tăng nhịp tim và đốt mỡ.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, hai tay thả tự nhiên hoặc co như đang chạy.', durationSeconds: 10 },
      { order: 2, instruction: 'Chạy bộ tại chỗ, nâng đầu gối ngang thắt lưng.', durationSeconds: 60 },
      { order: 3, instruction: 'Duy trì tốc độ đều, hít thở qua mũi và thở ra qua miệng.', durationSeconds: 300 },
    ],
    isActive: true,
  },
  {
    name: 'Nhảy dây',
    nameEn: 'Jump Rope',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 15,
    caloriesBurned: 150,
    imageUrl: null,
    description: 'Bài tập toàn thân hiệu quả cao, đốt nhiều calo.',
    steps: [
      { order: 1, instruction: 'Giữ tay cầm dây ở hai bên hông, dây phía sau.', durationSeconds: 5 },
      { order: 2, instruction: 'Xoay cổ tay để vung dây qua đầu và nhảy lên khi dây đến chân.', durationSeconds: 30 },
      { order: 3, instruction: 'Nhảy nhẹ nhàng trên mũi bàn chân, không giậm mạnh gót.', durationSeconds: 120 },
      { order: 4, instruction: 'Nghỉ 30 giây sau mỗi 2 phút, tổng thực hiện 10-15 phút.', durationSeconds: 300 },
    ],
    isActive: true,
  },
  {
    name: 'Bài tập Burpees',
    nameEn: 'Burpees',
    category: 'cardio',
    difficulty: 'hard',
    durationMinutes: 12,
    caloriesBurned: 130,
    imageUrl: null,
    description: 'Bài tập toàn thân cường độ cao, tăng sức mạnh và cardio.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, sau đó ngồi xổm và đặt hai tay xuống sàn.', durationSeconds: 5 },
      { order: 2, instruction: 'Bật chân ra sau vào tư thế hít đất.', durationSeconds: 5 },
      { order: 3, instruction: 'Thực hiện 1 cái hít đất (tùy chọn).', durationSeconds: 5 },
      { order: 4, instruction: 'Bật chân về tư thế xổm rồi nhảy lên, vỗ tay trên đầu.', durationSeconds: 5 },
      { order: 5, instruction: 'Thực hiện 10-15 lần, nghỉ 1 phút, lặp 3-5 hiệp.', durationSeconds: 120 },
    ],
    isActive: true,
  },
  {
    name: 'Leo núi tại chỗ',
    nameEn: 'Mountain Climbers',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 100,
    imageUrl: null,
    description: 'Tăng nhịp tim và tăng sức mạnh lõi cơ thể.',
    steps: [
      { order: 1, instruction: 'Bắt đầu ở tư thế hít đất thẳng, tay dưới vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Đưa đầu gối phải nhanh về phía ngực.', durationSeconds: 5 },
      { order: 3, instruction: 'Đổi chân nhanh chóng như đang leo núi.', durationSeconds: 30 },
      { order: 4, instruction: 'Duy trì hông thẳng, tốc độ nhanh trong 20-30 giây rồi nghỉ.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Nhảy bật cao',
    nameEn: 'Box Jumps',
    category: 'cardio',
    difficulty: 'hard',
    durationMinutes: 12,
    caloriesBurned: 120,
    imageUrl: null,
    description: 'Bài tập nổ lực kết hợp sức mạnh và cardio.',
    steps: [
      { order: 1, instruction: 'Đứng trước hộp hoặc bề mặt cao 30-60cm.', durationSeconds: 5 },
      { order: 2, instruction: 'Xổm xuống nhẹ, vung tay ra sau để lấy đà.', durationSeconds: 5 },
      { order: 3, instruction: 'Nhảy lên bề mặt, hạ cánh mềm trên mũi chân.', durationSeconds: 5 },
      { order: 4, instruction: 'Bước hoặc nhảy xuống, thực hiện 8-12 lần mỗi hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Đạp xe trên không',
    nameEn: 'Bicycle Crunches',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 90,
    imageUrl: null,
    description: 'Tăng cường cơ bụng và tim mạch kết hợp.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, tay đặt sau đầu, đầu gối co lên.', durationSeconds: 5 },
      { order: 2, instruction: 'Nâng vai khỏi sàn, xoay khuỷu tay trái về phía gối phải.', durationSeconds: 10 },
      { order: 3, instruction: 'Đồng thời duỗi thẳng chân trái ra, đổi bên liên tục.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 20-30 lần mỗi bên, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Nâng gối cao',
    nameEn: 'High Knees',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 85,
    imageUrl: null,
    description: 'Tăng nhịp tim và tăng cường cơ đùi trước.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, hai tay giơ ngang thắt lưng.', durationSeconds: 5 },
      { order: 2, instruction: 'Chạy tại chỗ, nâng đầu gối chạm tay.', durationSeconds: 10 },
      { order: 3, instruction: 'Duy trì tốc độ nhanh, hít thở đều.', durationSeconds: 60 },
      { order: 4, instruction: 'Thực hiện 30 giây rồi nghỉ 15 giây, lặp 5-8 lần.', durationSeconds: 120 },
    ],
    isActive: true,
  },
  {
    name: 'Nhảy chân tách',
    nameEn: 'Jumping Jacks',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 75,
    imageUrl: null,
    description: 'Bài tập khởi động toàn thân nhẹ nhàng và hiệu quả.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, hai tay thả dọc người.', durationSeconds: 5 },
      { order: 2, instruction: 'Nhảy dang hai chân sang hai bên, đồng thời giơ tay lên trên đầu.', durationSeconds: 10 },
      { order: 3, instruction: 'Nhảy về tư thế ban đầu, tiếp tục liên tục.', durationSeconds: 60 },
      { order: 4, instruction: 'Thực hiện 50-100 lần hoặc trong 2-3 phút.', durationSeconds: 120 },
    ],
    isActive: true,
  },
  {
    name: 'Hít đất thông thường',
    nameEn: 'Standard Push-ups',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 95,
    imageUrl: null,
    description: 'Tăng sức mạnh ngực, vai, tay và lõi cơ thể.',
    steps: [
      { order: 1, instruction: 'Nằm sấp, tay rộng hơn vai, chân duỗi thẳng.', durationSeconds: 5 },
      { order: 2, instruction: 'Hạ ngực xuống gần sàn, khuỷu tay hơi cong ra sau.', durationSeconds: 5 },
      { order: 3, instruction: 'Đẩy người lên về tư thế ban đầu.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 10-20 lần mỗi hiệp, 3-5 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Thảm lăn bụng',
    nameEn: 'Ab Rollout',
    category: 'cardio',
    difficulty: 'hard',
    durationMinutes: 12,
    caloriesBurned: 100,
    imageUrl: null,
    description: 'Tăng cường cơ bụng sâu và ổn định lõi.',
    steps: [
      { order: 1, instruction: 'Quỳ gối, cầm tay lăn (ab wheel) phía trước.', durationSeconds: 5 },
      { order: 2, instruction: 'Lăn bánh xe ra phía trước, duỗi thẳng cơ thể gần sàn.', durationSeconds: 10 },
      { order: 3, instruction: 'Co bụng kéo bánh xe về vị trí ban đầu.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 8-12 lần mỗi hiệp, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Nhảy bước dài',
    nameEn: 'Long Jump Steps',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 110,
    imageUrl: null,
    description: 'Tăng sức bền và nâng cao khả năng nhảy xa.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, hai tay thả.', durationSeconds: 5 },
      { order: 2, instruction: 'Nhảy bước dài về phía trước bằng cả hai chân.', durationSeconds: 10 },
      { order: 3, instruction: 'Hạ cánh mềm mại trên mũi chân, giữ thăng bằng.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 10-15 lần bước dài rồi quay lại, lặp 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Chạy nước rút tại chỗ',
    nameEn: 'Sprint in Place',
    category: 'cardio',
    difficulty: 'hard',
    durationMinutes: 8,
    caloriesBurned: 120,
    imageUrl: null,
    description: 'Bài tập cardio cường độ cao ngắn, đốt mỡ hiệu quả.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, chuẩn bị tư thế chạy.', durationSeconds: 5 },
      { order: 2, instruction: 'Chạy cực nhanh tại chỗ trong 20 giây hết sức.', durationSeconds: 20 },
      { order: 3, instruction: 'Nghỉ 40 giây đi bộ chậm tại chỗ.', durationSeconds: 40 },
      { order: 4, instruction: 'Lặp lại 8-10 vòng (HIIT kiểu tabata).', durationSeconds: 300 },
    ],
    isActive: true,
  },
  {
    name: 'Squat nhảy',
    nameEn: 'Jump Squats',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 115,
    imageUrl: null,
    description: 'Kết hợp sức mạnh chân và tim mạch trong một bài tập.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, chân rộng bằng vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Xổm xuống đến khi đùi song song sàn.', durationSeconds: 5 },
      { order: 3, instruction: 'Nhảy mạnh lên cao, duỗi thẳng người.', durationSeconds: 5 },
      { order: 4, instruction: 'Hạ cánh mềm mại, thực hiện 15-20 lần, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Dance Aerobic cơ bản',
    nameEn: 'Basic Aerobic Dance',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 20,
    caloriesBurned: 140,
    imageUrl: null,
    description: 'Bài tập nhảy aerobic vui nhộn, tăng nhịp tim và tinh thần.',
    steps: [
      { order: 1, instruction: 'Khởi động 3 phút nhảy nhẹ nhàng theo nhạc.', durationSeconds: 180 },
      { order: 2, instruction: 'Thực hiện các động tác cơ bản: bước sang phải trái, nhún chân.', durationSeconds: 300 },
      { order: 3, instruction: 'Tăng cường độ với nhảy và vung tay theo nhịp nhạc 10 phút.', durationSeconds: 600 },
      { order: 4, instruction: 'Hạ nhiệt 3 phút đi bộ nhẹ nhàng.', durationSeconds: 180 },
    ],
    isActive: true,
  },
  {
    name: 'Bơi cạn',
    nameEn: 'Dry Swimming',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 85,
    imageUrl: null,
    description: 'Mô phỏng động tác bơi lội, tăng cường toàn thân.',
    steps: [
      { order: 1, instruction: 'Nằm sấp, hai tay duỗi thẳng phía trên đầu.', durationSeconds: 5 },
      { order: 2, instruction: 'Đồng thời nâng tay phải và chân trái lên cao.', durationSeconds: 5 },
      { order: 3, instruction: 'Đổi bên liên tục như đang bơi ếch trong nước.', durationSeconds: 30 },
      { order: 4, instruction: 'Thực hiện 30 giây, nghỉ 10 giây, lặp 5-8 lần.', durationSeconds: 120 },
    ],
    isActive: true,
  },
  {
    name: 'Chạy bậc thang',
    nameEn: 'Stair Running',
    category: 'cardio',
    difficulty: 'hard',
    durationMinutes: 15,
    caloriesBurned: 160,
    imageUrl: null,
    description: 'Tăng cường sức bền và sức mạnh chân toàn diện.',
    steps: [
      { order: 1, instruction: 'Đứng trước cầu thang, chuẩn bị tư thế chạy.', durationSeconds: 10 },
      { order: 2, instruction: 'Chạy nhanh lên cầu thang, bước mỗi bậc hoặc nhảy 2 bậc.', durationSeconds: 30 },
      { order: 3, instruction: 'Đi bộ xuống nhẹ nhàng để phục hồi.', durationSeconds: 30 },
      { order: 4, instruction: 'Lặp lại 5-10 lần, nghỉ 1-2 phút giữa hiệp.', durationSeconds: 300 },
    ],
    isActive: true,
  },
  {
    name: 'Nhảy lên bục',
    nameEn: 'Step Ups',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 12,
    caloriesBurned: 100,
    imageUrl: null,
    description: 'Bài tập cardio nhẹ nhàng phù hợp mọi lứa tuổi.',
    steps: [
      { order: 1, instruction: 'Đứng trước bậc thang hoặc hộp cao 20-30cm.', durationSeconds: 5 },
      { order: 2, instruction: 'Bước chân phải lên bục, rồi chân trái theo.', durationSeconds: 5 },
      { order: 3, instruction: 'Bước chân phải xuống, chân trái theo.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 1 phút, nghỉ 30 giây, lặp 5-8 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Plank kết hợp chân',
    nameEn: 'Plank with Leg Lift',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 8,
    caloriesBurned: 75,
    imageUrl: null,
    description: 'Tăng cường lõi và mông, nâng cao sức bền.',
    steps: [
      { order: 1, instruction: 'Vào tư thế plank trên khuỷu tay, toàn thân thẳng.', durationSeconds: 10 },
      { order: 2, instruction: 'Nâng chân phải lên cao 10-15cm, giữ 2-3 giây.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ xuống và đổi chân, thực hiện xen kẽ.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 30 giây mỗi bên, 3-5 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tuck Jump',
    nameEn: 'Tuck Jumps',
    category: 'cardio',
    difficulty: 'hard',
    durationMinutes: 8,
    caloriesBurned: 125,
    imageUrl: null,
    description: 'Nhảy co gối nhanh, tăng sức nổ và nhịp tim.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, chân rộng bằng hông.', durationSeconds: 5 },
      { order: 2, instruction: 'Nhảy lên cao, đưa hai đầu gối về phía ngực.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ xuống mềm mại, lập tức nhảy lên lần tiếp theo.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 10 lần liên tiếp, nghỉ 1 phút, lặp 3-5 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Skater Jump',
    nameEn: 'Skater Jumps',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 105,
    imageUrl: null,
    description: 'Nhảy bên mô phỏng trượt băng, tăng sức mạnh mông.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, nhảy sang bên phải bằng chân phải.', durationSeconds: 5 },
      { order: 2, instruction: 'Hạ cánh trên chân phải, chân trái đưa ra sau chéo.', durationSeconds: 5 },
      { order: 3, instruction: 'Nhảy sang trái bằng chân trái, chân phải đưa ra sau chéo.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 20 lần mỗi bên, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Bear Crawl',
    nameEn: 'Bear Crawl',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 8,
    caloriesBurned: 90,
    imageUrl: null,
    description: 'Bò gấu tăng sức mạnh toàn thân và cardio.',
    steps: [
      { order: 1, instruction: 'Bắt đầu ở tư thế bốn điểm chống, nâng gối lên khỏi sàn 2-3cm.', durationSeconds: 5 },
      { order: 2, instruction: 'Di chuyển về phía trước bằng cách cùng lúc đưa tay phải và chân trái.', durationSeconds: 10 },
      { order: 3, instruction: 'Tiếp tục bò về phía trước 5-10 mét.', durationSeconds: 30 },
      { order: 4, instruction: 'Bò lùi về vị trí ban đầu. Lặp lại 3-5 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Nhảy dang chân xen kẽ',
    nameEn: 'Alternating Leg Jumps',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 70,
    imageUrl: null,
    description: 'Bài tập cardio nhẹ nhàng với nhảy xen kẽ chân.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, chân trái trước, chân phải sau.', durationSeconds: 5 },
      { order: 2, instruction: 'Nhảy lên đổi vị trí chân, chân phải về trước.', durationSeconds: 5 },
      { order: 3, instruction: 'Tiếp tục nhảy đổi chân liên tục, nhịp nhàng.', durationSeconds: 30 },
      { order: 4, instruction: 'Thực hiện 1 phút, nghỉ 20 giây, lặp 5 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Lateral Shuffle',
    nameEn: 'Lateral Shuffle',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 10,
    caloriesBurned: 80,
    imageUrl: null,
    description: 'Di chuyển ngang tăng tốc độ phản xạ và cardio.',
    steps: [
      { order: 1, instruction: 'Đứng tư thế thấp nhẹ, đầu gối hơi khuỵu.', durationSeconds: 5 },
      { order: 2, instruction: 'Bước sang phải 3-5 bước nhanh.', durationSeconds: 10 },
      { order: 3, instruction: 'Bước sang trái 3-5 bước nhanh.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện liên tục 1 phút, nghỉ 20 giây, lặp 5-8 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Inchworm',
    nameEn: 'Inchworm',
    category: 'cardio',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 88,
    imageUrl: null,
    description: 'Bài tập toàn thân tăng cường linh hoạt và sức mạnh.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cúi người về phía trước chạm tay xuống sàn.', durationSeconds: 10 },
      { order: 2, instruction: 'Đi bằng tay ra phía trước đến tư thế hít đất.', durationSeconds: 10 },
      { order: 3, instruction: 'Thực hiện 1 cái hít đất (tùy chọn).', durationSeconds: 5 },
      { order: 4, instruction: 'Đi bằng tay ngược lại về, đứng thẳng. Lặp 8-10 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Nhảy lò cò',
    nameEn: 'Hopscotch Cardio',
    category: 'cardio',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 72,
    imageUrl: null,
    description: 'Nhảy lò cò tăng sức bền tim mạch và sự linh hoạt.',
    steps: [
      { order: 1, instruction: 'Nhảy hai chân xuống khoảng cách rộng, sau đó nhảy một chân.', durationSeconds: 10 },
      { order: 2, instruction: 'Tiếp tục nhảy xen kẽ hai chân và một chân theo nhịp đều.', durationSeconds: 30 },
      { order: 3, instruction: 'Duy trì nhịp độ đều trong 30-45 giây rồi nghỉ 15 giây.', durationSeconds: 45 },
      { order: 4, instruction: 'Lặp lại 5-8 vòng.', durationSeconds: 120 },
    ],
    isActive: true,
  },

  // ========================
  // WEIGHTS (25 bài)
  // ========================
  {
    name: 'Squat tạ đơn',
    nameEn: 'Dumbbell Squat',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 120,
    imageUrl: null,
    description: 'Tăng cường cơ đùi, mông và lưng dưới với tạ đơn.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ đơn hai tay thả dọc người.', durationSeconds: 5 },
      { order: 2, instruction: 'Chân rộng bằng vai, mũi chân hướng hơi ra ngoài.', durationSeconds: 5 },
      { order: 3, instruction: 'Xổm xuống đến khi đùi song song sàn, lưng thẳng.', durationSeconds: 10 },
      { order: 4, instruction: 'Đứng lên. Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Đẩy ngực với tạ đơn',
    nameEn: 'Dumbbell Bench Press',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 15,
    caloriesBurned: 130,
    imageUrl: null,
    description: 'Tăng cường cơ ngực, vai trước và tay sau.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa trên ghế tập, cầm tạ đơn hai tay ngang ngực.', durationSeconds: 5 },
      { order: 2, instruction: 'Đẩy tạ lên thẳng đứng, không khóa khuỷu tay.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ tạ xuống chậm rãi về vị trí ban đầu.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 10-12 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Gập tay với tạ đơn',
    nameEn: 'Dumbbell Bicep Curl',
    category: 'weights',
    difficulty: 'easy',
    durationMinutes: 10,
    caloriesBurned: 90,
    imageUrl: null,
    description: 'Tăng cường cơ bắp tay trước.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ đơn hai tay, lòng bàn tay ngửa lên.', durationSeconds: 5 },
      { order: 2, instruction: 'Co tay lên đưa tạ về phía vai, khuỷu tay sát người.', durationSeconds: 5 },
      { order: 3, instruction: 'Giữ 1 giây ở đỉnh, hạ xuống chậm rãi.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Đẩy vai với tạ đơn',
    nameEn: 'Dumbbell Shoulder Press',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 110,
    imageUrl: null,
    description: 'Tăng cường cơ vai ba đầu và tay sau.',
    steps: [
      { order: 1, instruction: 'Ngồi hoặc đứng, cầm tạ đơn ngang vai, khuỷu tay vuông góc.', durationSeconds: 5 },
      { order: 2, instruction: 'Đẩy tạ lên thẳng đứng qua đầu.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ xuống chậm rãi về vị trí ban đầu.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 10-12 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Deadlift với tạ ấm',
    nameEn: 'Kettlebell Deadlift',
    category: 'weights',
    difficulty: 'hard',
    durationMinutes: 15,
    caloriesBurned: 150,
    imageUrl: null,
    description: 'Tăng cường toàn bộ chuỗi cơ sau lưng và chân.',
    steps: [
      { order: 1, instruction: 'Đứng với tạ ấm giữa hai chân rộng bằng vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Khuỵu hông về phía sau, lưng thẳng, nắm cán tạ.', durationSeconds: 10 },
      { order: 3, instruction: 'Đứng dậy bằng cách đẩy gót chân xuống đất, đẩy hông về trước.', durationSeconds: 10 },
      { order: 4, instruction: 'Hạ tạ xuống chậm rãi. Thực hiện 8-10 lần, 3-5 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Kéo tạ gập người',
    nameEn: 'Bent-Over Dumbbell Row',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 120,
    imageUrl: null,
    description: 'Tăng cường cơ lưng giữa và bắp tay trước.',
    steps: [
      { order: 1, instruction: 'Đứng cúi người về phía trước 45 độ, cầm tạ hai tay.', durationSeconds: 5 },
      { order: 2, instruction: 'Kéo tạ lên về phía hông, khuỷu tay sát người.', durationSeconds: 5 },
      { order: 3, instruction: 'Siết cơ lưng ở đỉnh, hạ xuống chậm.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 10-12 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Lunges với tạ',
    nameEn: 'Weighted Lunges',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 115,
    imageUrl: null,
    description: 'Tăng cường cơ đùi, mông và cải thiện thăng bằng.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ đơn hai tay thả dọc người.', durationSeconds: 5 },
      { order: 2, instruction: 'Bước chân phải về phía trước, hạ gối trái xuống gần sàn.', durationSeconds: 10 },
      { order: 3, instruction: 'Đứng dậy và đổi chân.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 12-15 lần mỗi chân, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Tricep dips với tạ',
    nameEn: 'Tricep Dips',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 95,
    imageUrl: null,
    description: 'Tăng cường cơ tay sau (tricep).',
    steps: [
      { order: 1, instruction: 'Ngồi trên ghế, tay giữ mép ghế, chân duỗi thẳng về trước.', durationSeconds: 5 },
      { order: 2, instruction: 'Hạ người xuống bằng cách co khuỷu tay.', durationSeconds: 5 },
      { order: 3, instruction: 'Đẩy người lên về vị trí ban đầu.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 10-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Lateral raise với tạ đơn',
    nameEn: 'Dumbbell Lateral Raise',
    category: 'weights',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 80,
    imageUrl: null,
    description: 'Tăng cường cơ vai bên.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ đơn hai tay thả dọc người.', durationSeconds: 5 },
      { order: 2, instruction: 'Nâng tay lên ngang vai, giữ tay hơi cong.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ xuống chậm rãi.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Romanian Deadlift tạ đơn',
    nameEn: 'Romanian Dumbbell Deadlift',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 125,
    imageUrl: null,
    description: 'Tập trung cơ gân kheo và mông.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ trước đùi.', durationSeconds: 5 },
      { order: 2, instruction: 'Giữ lưng thẳng, cúi người về phía trước bằng cách đẩy hông ra sau.', durationSeconds: 10 },
      { order: 3, instruction: 'Hạ tạ dọc chân đến khi cảm thấy căng cơ gân kheo.', durationSeconds: 10 },
      { order: 4, instruction: 'Đứng dậy, siết cơ mông. Thực hiện 10-12 lần, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Calf raise với tạ',
    nameEn: 'Weighted Calf Raise',
    category: 'weights',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 70,
    imageUrl: null,
    description: 'Tăng cường cơ bắp chân.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ hai tay, đứng trên mép bậc thang hoặc sàn.', durationSeconds: 5 },
      { order: 2, instruction: 'Nâng cao gót chân lên hết cỡ, siết cơ bắp chân.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ gót xuống chậm, có thể hạ thấp hơn mặt phẳng nếu đứng trên bậc.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 15-20 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Pull-over tạ đơn',
    nameEn: 'Dumbbell Pullover',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 100,
    imageUrl: null,
    description: 'Tăng cường cơ lưng và ngực, mở rộng lồng ngực.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa trên ghế tập, cầm tạ đơn bằng cả hai tay phía trên ngực.', durationSeconds: 5 },
      { order: 2, instruction: 'Từ từ hạ tạ về phía sau đầu, cánh tay hơi cong.', durationSeconds: 10 },
      { order: 3, instruction: 'Kéo tạ về vị trí ban đầu bằng cơ lưng và ngực.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 10-12 lần, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Arnold Press',
    nameEn: 'Arnold Press',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 110,
    imageUrl: null,
    description: 'Đẩy vai biến thể kết hợp xoay, tăng cơ vai toàn diện.',
    steps: [
      { order: 1, instruction: 'Ngồi, cầm tạ ngang cằm, lòng bàn tay hướng vào mặt.', durationSeconds: 5 },
      { order: 2, instruction: 'Đẩy tạ lên đồng thời xoay tay ra ngoài 180 độ.', durationSeconds: 10 },
      { order: 3, instruction: 'Hạ xuống và xoay tay về vị trí ban đầu.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 10-12 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Hack squat tạ ấm',
    nameEn: 'Kettlebell Hack Squat',
    category: 'weights',
    difficulty: 'hard',
    durationMinutes: 15,
    caloriesBurned: 140,
    imageUrl: null,
    description: 'Biến thể squat tập trung cơ tứ đầu đùi.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, tạ ấm cầm sau lưng ở phần thấp.', durationSeconds: 5 },
      { order: 2, instruction: 'Xổm xuống đến khi đùi song song sàn.', durationSeconds: 10 },
      { order: 3, instruction: 'Đứng dậy, siết cơ đùi ở đỉnh.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 8-10 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Hammer curl',
    nameEn: 'Hammer Curl',
    category: 'weights',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 80,
    imageUrl: null,
    description: 'Tăng cường cơ bắp tay và cơ brachialis.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ đơn hai tay, ngón cái hướng lên.', durationSeconds: 5 },
      { order: 2, instruction: 'Co tay đưa tạ lên vai, giữ ngón cái hướng lên.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ xuống chậm rãi về vị trí ban đầu.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Sumo squat tạ ấm',
    nameEn: 'Kettlebell Sumo Squat',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 125,
    imageUrl: null,
    description: 'Tăng cường cơ đùi trong, mông và háng.',
    steps: [
      { order: 1, instruction: 'Đứng chân rộng hơn vai, mũi chân xoay 45 độ ra ngoài, cầm tạ ấm giữa hai chân.', durationSeconds: 5 },
      { order: 2, instruction: 'Xổm xuống thẳng, lưng thẳng.', durationSeconds: 10 },
      { order: 3, instruction: 'Đứng dậy, siết cơ mông và đùi trong.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Đẩy ngực với dây kéo',
    nameEn: 'Cable Chest Press',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 115,
    imageUrl: null,
    description: 'Tập ngực với lực kéo dây giúp giữ căng cơ liên tục.',
    steps: [
      { order: 1, instruction: 'Điều chỉnh dây kéo ngang ngực, đứng giữa máy.', durationSeconds: 5 },
      { order: 2, instruction: 'Cầm tay cầm, đẩy ra phía trước chụm lại trước ngực.', durationSeconds: 10 },
      { order: 3, instruction: 'Mở rộng chậm rãi về vị trí ban đầu.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Upright row tạ đơn',
    nameEn: 'Dumbbell Upright Row',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 100,
    imageUrl: null,
    description: 'Tăng cường cơ vai và thang cơ.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ đơn hai tay trước đùi.', durationSeconds: 5 },
      { order: 2, instruction: 'Kéo tạ lên dọc theo cơ thể đến ngang cằm, khuỷu tay cao hơn tay.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ xuống chậm rãi.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 10-12 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Plank với tạ',
    nameEn: 'Weighted Plank',
    category: 'weights',
    difficulty: 'hard',
    durationMinutes: 10,
    caloriesBurned: 95,
    imageUrl: null,
    description: 'Tăng cường lõi với thêm tải trọng.',
    steps: [
      { order: 1, instruction: 'Vào tư thế plank trên khuỷu tay, nhờ người khác đặt tạ đĩa lên lưng.', durationSeconds: 10 },
      { order: 2, instruction: 'Giữ toàn thân thẳng, không để hông trũng xuống.', durationSeconds: 10 },
      { order: 3, instruction: 'Hít thở đều, giữ tư thế 20-60 giây.', durationSeconds: 60 },
      { order: 4, instruction: 'Nghỉ 30 giây, lặp 3-5 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Front raise tạ đơn',
    nameEn: 'Dumbbell Front Raise',
    category: 'weights',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 75,
    imageUrl: null,
    description: 'Tăng cường cơ vai trước.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, cầm tạ đơn hai tay trước đùi.', durationSeconds: 5 },
      { order: 2, instruction: 'Nâng tay thẳng lên ngang vai, giữ cánh tay thẳng.', durationSeconds: 5 },
      { order: 3, instruction: 'Hạ xuống chậm rãi.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Good morning với tạ',
    nameEn: 'Dumbbell Good Morning',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 110,
    imageUrl: null,
    description: 'Tăng cường cơ gân kheo và lưng dưới.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, đặt tạ đơn trên vai hoặc giữ trước ngực.', durationSeconds: 5 },
      { order: 2, instruction: 'Giữ lưng thẳng, cúi người về phía trước từ khớp hông.', durationSeconds: 10 },
      { order: 3, instruction: 'Hạ xuống đến khi lưng song song sàn hoặc cảm thấy căng gân kheo.', durationSeconds: 10 },
      { order: 4, instruction: 'Đứng dậy. Thực hiện 10-12 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Hip thrust với tạ',
    nameEn: 'Weighted Hip Thrust',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 12,
    caloriesBurned: 120,
    imageUrl: null,
    description: 'Tăng cường cơ mông tối đa.',
    steps: [
      { order: 1, instruction: 'Ngồi tựa lưng vào ghế tập, đặt tạ đĩa trên hông.', durationSeconds: 5 },
      { order: 2, instruction: 'Đặt chân phẳng trên sàn, đẩy hông lên đến khi cơ thể tạo đường thẳng.', durationSeconds: 10 },
      { order: 3, instruction: 'Siết cơ mông ở đỉnh, giữ 1-2 giây.', durationSeconds: 5 },
      { order: 4, instruction: 'Hạ xuống chậm. Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Zottman curl',
    nameEn: 'Zottman Curl',
    category: 'weights',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 90,
    imageUrl: null,
    description: 'Tăng cường toàn bộ cơ tay trước và sau.',
    steps: [
      { order: 1, instruction: 'Đứng, cầm tạ đơn, lòng bàn tay ngửa lên.', durationSeconds: 5 },
      { order: 2, instruction: 'Co tay lên tư thế curl thông thường.', durationSeconds: 5 },
      { order: 3, instruction: 'Xoay cổ tay 180 độ (lòng bàn tay úp xuống) ở đỉnh.', durationSeconds: 5 },
      { order: 4, instruction: 'Hạ xuống chậm với lòng bàn tay úp. Lặp 10-12 lần, 3 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Bulgarian split squat tạ',
    nameEn: 'Bulgarian Split Squat',
    category: 'weights',
    difficulty: 'hard',
    durationMinutes: 15,
    caloriesBurned: 145,
    imageUrl: null,
    description: 'Squat một chân nâng cao, tăng cường đùi và mông mỗi bên.',
    steps: [
      { order: 1, instruction: 'Đứng trước ghế, đặt chân phải lên ghế phía sau.', durationSeconds: 5 },
      { order: 2, instruction: 'Cầm tạ đơn hai tay, hạ gối phải xuống gần sàn.', durationSeconds: 10 },
      { order: 3, instruction: 'Đứng dậy bằng chân trái.', durationSeconds: 10 },
      { order: 4, instruction: 'Thực hiện 10-12 lần rồi đổi chân, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Incline push-up',
    nameEn: 'Incline Push-up',
    category: 'weights',
    difficulty: 'easy',
    durationMinutes: 8,
    caloriesBurned: 75,
    imageUrl: null,
    description: 'Hít đất trên bề mặt nghiêng, giảm lực tập trung cơ ngực trên.',
    steps: [
      { order: 1, instruction: 'Đặt tay lên ghế hoặc bục cao, chân duỗi thẳng sau.', durationSeconds: 5 },
      { order: 2, instruction: 'Hạ ngực về phía bề mặt, khuỷu tay gập 90 độ.', durationSeconds: 5 },
      { order: 3, instruction: 'Đẩy người lên về tư thế ban đầu.', durationSeconds: 5 },
      { order: 4, instruction: 'Thực hiện 12-15 lần, 3-4 hiệp.', durationSeconds: 60 },
    ],
    isActive: true,
  },

  // ========================
  // STRETCHING (25 bài)
  // ========================
  {
    name: 'Giãn cơ gân kheo',
    nameEn: 'Hamstring Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Kéo giãn cơ gân kheo, giảm căng cứng sau tập luyện.',
    steps: [
      { order: 1, instruction: 'Ngồi trên sàn, duỗi thẳng hai chân.', durationSeconds: 5 },
      { order: 2, instruction: 'Cúi người về phía trước, cố gắng chạm ngón tay vào ngón chân.', durationSeconds: 15 },
      { order: 3, instruction: 'Giữ tư thế 30 giây, hít thở đều.', durationSeconds: 30 },
      { order: 4, instruction: 'Thực hiện 3 lần, nghỉ 10 giây giữa mỗi lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ tứ đầu đùi',
    nameEn: 'Quadriceps Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 28,
    imageUrl: null,
    description: 'Giảm căng cứng cơ đùi trước sau chạy bộ và squat.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, giữ tay tựa vào tường nếu cần.', durationSeconds: 5 },
      { order: 2, instruction: 'Co chân phải lên, nắm bàn chân kéo về phía mông.', durationSeconds: 10 },
      { order: 3, instruction: 'Giữ đùi thẳng, cảm nhận sự kéo căng ở đùi trước.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30 giây rồi đổi chân, lặp 3 lần mỗi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ vai và cánh tay',
    nameEn: 'Shoulder and Arm Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 25,
    imageUrl: null,
    description: 'Giảm căng thẳng cơ vai sau làm việc văn phòng.',
    steps: [
      { order: 1, instruction: 'Đưa cánh tay phải ngang qua ngực.', durationSeconds: 5 },
      { order: 2, instruction: 'Dùng tay trái kéo cánh tay phải vào ngực.', durationSeconds: 15 },
      { order: 3, instruction: 'Giữ 30 giây, cảm nhận giãn cơ ở vai và cánh tay.', durationSeconds: 30 },
      { order: 4, instruction: 'Đổi bên, lặp 3 lần mỗi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Tư thế con mèo — giãn cột sống',
    nameEn: 'Spinal Cat Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 28,
    imageUrl: null,
    description: 'Tăng linh hoạt cột sống, giảm đau lưng.',
    steps: [
      { order: 1, instruction: 'Quỳ bốn điểm chống, tay thẳng dưới vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Hít vào, cong lưng lên (tư thế mèo), cúi đầu vào.', durationSeconds: 10 },
      { order: 3, instruction: 'Thở ra, cong lưng xuống (tư thế bò), ngẩng đầu lên.', durationSeconds: 10 },
      { order: 4, instruction: 'Lặp lại nhịp nhàng 10-15 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn lưng dưới',
    nameEn: 'Lower Back Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 6,
    caloriesBurned: 27,
    imageUrl: null,
    description: 'Giảm đau lưng dưới và cải thiện linh hoạt cột sống thắt lưng.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, hai chân duỗi thẳng.', durationSeconds: 5 },
      { order: 2, instruction: 'Co hai gối lên ngực, ôm bằng hai tay.', durationSeconds: 15 },
      { order: 3, instruction: 'Kéo gối nhẹ vào ngực, cảm nhận giãn lưng dưới.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30-60 giây, thở đều.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ cổ',
    nameEn: 'Neck Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 22,
    imageUrl: null,
    description: 'Giảm căng cứng cổ và vai sau ngồi lâu.',
    steps: [
      { order: 1, instruction: 'Ngồi hoặc đứng thẳng, thả lỏng vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Nghiêng đầu sang phải, đặt tay phải lên đầu kéo nhẹ.', durationSeconds: 20 },
      { order: 3, instruction: 'Giữ 20-30 giây, cảm nhận giãn cơ cổ bên trái.', durationSeconds: 30 },
      { order: 4, instruction: 'Đổi bên, lặp 3 lần mỗi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ ngực',
    nameEn: 'Chest Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 25,
    imageUrl: null,
    description: 'Mở rộng ngực, cải thiện tư thế và giảm căng ngực sau tập.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, đan tay sau lưng.', durationSeconds: 5 },
      { order: 2, instruction: 'Kéo thẳng tay ra sau, mở rộng ngực và vai.', durationSeconds: 15 },
      { order: 3, instruction: 'Ngẩng đầu nhìn lên, cảm nhận giãn cơ ngực.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 20-30 giây, lặp 3 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ bắp chân',
    nameEn: 'Calf Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 25,
    imageUrl: null,
    description: 'Giảm căng cứng cơ bắp chân sau chạy bộ.',
    steps: [
      { order: 1, instruction: 'Đứng trước tường, đặt tay lên tường.', durationSeconds: 5 },
      { order: 2, instruction: 'Bước chân phải ra sau, giữ gót chân ép xuống sàn.', durationSeconds: 10 },
      { order: 3, instruction: 'Cúi người về tường cho đến khi căng cơ bắp chân sau.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30 giây rồi đổi chân, lặp 3 lần mỗi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ hông flexor',
    nameEn: 'Hip Flexor Stretch',
    category: 'stretching',
    difficulty: 'medium',
    durationMinutes: 7,
    caloriesBurned: 32,
    imageUrl: null,
    description: 'Kéo giãn cơ gấp hông, giảm căng thẳng do ngồi lâu.',
    steps: [
      { order: 1, instruction: 'Quỳ trên chân phải, chân trái bước ra phía trước.', durationSeconds: 5 },
      { order: 2, instruction: 'Đẩy hông về phía trước nhẹ nhàng đến khi cảm thấy căng ở hông phải.', durationSeconds: 15 },
      { order: 3, instruction: 'Giữ lưng thẳng, tránh cong lưng.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30 giây rồi đổi bên, lặp 3 lần mỗi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ đùi trong',
    nameEn: 'Inner Thigh Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 6,
    caloriesBurned: 28,
    imageUrl: null,
    description: 'Kéo giãn cơ đùi trong và háng, tăng linh hoạt hông.',
    steps: [
      { order: 1, instruction: 'Ngồi bắt chéo chân (tư thế bướm), lòng bàn chân chạm vào nhau.', durationSeconds: 5 },
      { order: 2, instruction: 'Dùng tay nhẹ nhàng ép đầu gối xuống sàn.', durationSeconds: 15 },
      { order: 3, instruction: 'Cúi người về phía trước nhẹ để tăng độ giãn.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30-60 giây, lặp 3 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ lưng giữa',
    nameEn: 'Mid Back Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 25,
    imageUrl: null,
    description: 'Giảm căng cứng lưng giữa sau ngồi làm việc.',
    steps: [
      { order: 1, instruction: 'Ngồi trên ghế, hai tay đan vào nhau trước ngực.', durationSeconds: 5 },
      { order: 2, instruction: 'Đẩy tay ra phía trước, khum lưng về sau như một vòng tròn.', durationSeconds: 15 },
      { order: 3, instruction: 'Cảm nhận giãn ở lưng giữa và hai bả vai.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 20-30 giây, lặp 3-5 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Pigeon nằm (giãn hông nằm ngửa)',
    nameEn: 'Supine Pigeon Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 7,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Kéo giãn hông và cơ tháp nhẹ nhàng.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, co hai gối lên.', durationSeconds: 5 },
      { order: 2, instruction: 'Đặt mắt cá chân phải lên đùi trái.', durationSeconds: 10 },
      { order: 3, instruction: 'Kéo chân trái về phía ngực đến khi cảm thấy căng hông phải.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30-60 giây rồi đổi bên.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ cột sống xoay nằm',
    nameEn: 'Supine Spinal Twist',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 6,
    caloriesBurned: 25,
    imageUrl: null,
    description: 'Xoay cột sống nhẹ nhàng, giảm đau lưng dưới và hông.',
    steps: [
      { order: 1, instruction: 'Nằm ngửa, co gối phải lên.', durationSeconds: 5 },
      { order: 2, instruction: 'Kéo gối phải sang trái, vai phải ép xuống sàn.', durationSeconds: 15 },
      { order: 3, instruction: 'Giơ tay phải ra ngang, mắt nhìn sang phải.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30-60 giây rồi đổi bên.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ tay sau (tricep)',
    nameEn: 'Tricep Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 4,
    caloriesBurned: 20,
    imageUrl: null,
    description: 'Kéo giãn cơ tay sau sau khi tập đẩy.',
    steps: [
      { order: 1, instruction: 'Giơ tay phải lên, gập khuỷu tay đưa bàn tay xuống sau đầu.', durationSeconds: 5 },
      { order: 2, instruction: 'Dùng tay trái kéo khuỷu tay phải sang trái.', durationSeconds: 10 },
      { order: 3, instruction: 'Cảm nhận giãn ở cơ tay sau.', durationSeconds: 20 },
      { order: 4, instruction: 'Giữ 20-30 giây rồi đổi bên, lặp 3 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ mông (hình số 4)',
    nameEn: 'Figure Four Glute Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 6,
    caloriesBurned: 28,
    imageUrl: null,
    description: 'Kéo giãn cơ mông và hông sâu hiệu quả.',
    steps: [
      { order: 1, instruction: 'Ngồi trên ghế, đặt mắt cá chân phải lên đùi trái.', durationSeconds: 5 },
      { order: 2, instruction: 'Cúi người về phía trước nhẹ nhàng.', durationSeconds: 10 },
      { order: 3, instruction: 'Cảm nhận giãn ở mông và hông phải.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30-45 giây rồi đổi bên.', durationSeconds: 45 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ Piriformis đứng',
    nameEn: 'Standing Piriformis Stretch',
    category: 'stretching',
    difficulty: 'medium',
    durationMinutes: 6,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Kéo giãn cơ tháp giúp giảm đau thần kinh tọa.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, bước chân phải lên bậc thang hoặc ghế thấp.', durationSeconds: 5 },
      { order: 2, instruction: 'Xoay mắt cá chân ra ngoài, gối hướng ra ngoài.', durationSeconds: 10 },
      { order: 3, instruction: 'Cúi người về phía trước cho đến khi cảm thấy căng ở hông.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30 giây rồi đổi bên, lặp 3 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ cẳng tay',
    nameEn: 'Forearm Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 4,
    caloriesBurned: 20,
    imageUrl: null,
    description: 'Kéo giãn cơ cẳng tay, phòng ngừa chấn thương cổ tay.',
    steps: [
      { order: 1, instruction: 'Duỗi thẳng tay phải ra phía trước, lòng bàn tay ngửa lên.', durationSeconds: 5 },
      { order: 2, instruction: 'Dùng tay trái kéo các ngón tay phải xuống dưới.', durationSeconds: 10 },
      { order: 3, instruction: 'Cảm nhận giãn ở cẳng tay trên.', durationSeconds: 20 },
      { order: 4, instruction: 'Lật ngửa bàn tay, kéo ngược lại. Lặp 3 lần mỗi bên.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ IT band (đùi ngoài)',
    nameEn: 'IT Band Stretch',
    category: 'stretching',
    difficulty: 'medium',
    durationMinutes: 6,
    caloriesBurned: 28,
    imageUrl: null,
    description: 'Kéo giãn dải chậu chày, phòng ngừa đau đầu gối.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, bắt chéo chân phải sau chân trái.', durationSeconds: 5 },
      { order: 2, instruction: 'Nghiêng người sang trái, tay phải giơ lên cao.', durationSeconds: 15 },
      { order: 3, instruction: 'Cảm nhận giãn ở đùi ngoài chân phải.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30 giây rồi đổi bên, lặp 3 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: "World's Greatest Stretch",
    nameEn: "World's Greatest Stretch",
    category: 'stretching',
    difficulty: 'medium',
    durationMinutes: 10,
    caloriesBurned: 45,
    imageUrl: null,
    description: 'Giãn toàn thân toàn diện nhất trong một động tác.',
    steps: [
      { order: 1, instruction: 'Bước chân phải lên phía trước, tay phải chạm sàn cạnh bàn chân.', durationSeconds: 10 },
      { order: 2, instruction: 'Xoay người sang phải, giơ tay phải lên trời.', durationSeconds: 15 },
      { order: 3, instruction: 'Hạ tay về, đẩy hông lên tư thế chó úp mặt ngắn.', durationSeconds: 10 },
      { order: 4, instruction: 'Lặp lại 5 lần rồi đổi bên.', durationSeconds: 120 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ ngực với băng ghế',
    nameEn: 'Bench Chest Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 22,
    imageUrl: null,
    description: 'Mở rộng cơ ngực và cải thiện tư thế gù lưng.',
    steps: [
      { order: 1, instruction: 'Ngồi trên ghế, đan tay sau gáy.', durationSeconds: 5 },
      { order: 2, instruction: 'Kéo khuỷu tay ra sau và ngửa lưng nhẹ về phía tựa ghế.', durationSeconds: 15 },
      { order: 3, instruction: 'Hít vào sâu để mở rộng lồng ngực.', durationSeconds: 20 },
      { order: 4, instruction: 'Giữ 20-30 giây, lặp 3-5 lần.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ bụng (Sphinx)',
    nameEn: 'Sphinx Pose Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 25,
    imageUrl: null,
    description: 'Kéo giãn cơ bụng và cột sống lưng sau gập bụng.',
    steps: [
      { order: 1, instruction: 'Nằm sấp, tựa khuỷu tay xuống sàn, khuỷu tay dưới vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Đẩy ngực lên nhẹ nhàng, thả lỏng lưng dưới và bụng.', durationSeconds: 15 },
      { order: 3, instruction: 'Giữ tư thế, hít thở sâu, cảm nhận giãn cơ bụng.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30-60 giây, lặp 3 lần.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ toàn thân đứng',
    nameEn: 'Full Body Standing Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 7,
    caloriesBurned: 30,
    imageUrl: null,
    description: 'Giãn cơ toàn thân đứng, phù hợp khởi động hoặc hạ nhiệt.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, giơ tay lên cao, kéo dài từ gót đến ngón tay.', durationSeconds: 15 },
      { order: 2, instruction: 'Nghiêng sang phải rồi sang trái, mỗi bên 20 giây.', durationSeconds: 40 },
      { order: 3, instruction: 'Cúi người về trước, tay chạm sàn, giữ 20 giây.', durationSeconds: 20 },
      { order: 4, instruction: 'Đứng lên, vươn tay ra sau, ngửa người nhẹ, giữ 20 giây.', durationSeconds: 20 },
    ],
    isActive: true,
  },
  {
    name: 'Plyometric stretch — Leg Swing',
    nameEn: 'Dynamic Leg Swing',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 35,
    imageUrl: null,
    description: 'Giãn động cơ hông và đùi, tốt cho khởi động trước chạy.',
    steps: [
      { order: 1, instruction: 'Đứng thẳng, giữ tay tựa tường cho thăng bằng.', durationSeconds: 5 },
      { order: 2, instruction: 'Đung đưa chân phải tới lui tự nhiên, biên độ tăng dần.', durationSeconds: 30 },
      { order: 3, instruction: 'Sau 15 lần đổi đung đưa ngang (trái phải) thêm 15 lần.', durationSeconds: 30 },
      { order: 4, instruction: 'Đổi chân trái, lặp lại tương tự.', durationSeconds: 60 },
    ],
    isActive: true,
  },
  {
    name: 'Ankle Circles — giãn cổ chân',
    nameEn: 'Ankle Circles',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 4,
    caloriesBurned: 18,
    imageUrl: null,
    description: 'Tăng linh hoạt khớp cổ chân, phòng ngừa bong gân.',
    steps: [
      { order: 1, instruction: 'Ngồi hoặc đứng, nâng chân phải lên khỏi sàn.', durationSeconds: 5 },
      { order: 2, instruction: 'Xoay cổ chân theo chiều kim đồng hồ 10 lần.', durationSeconds: 15 },
      { order: 3, instruction: 'Xoay ngược chiều 10 lần.', durationSeconds: 15 },
      { order: 4, instruction: 'Đổi chân, lặp lại.', durationSeconds: 30 },
    ],
    isActive: true,
  },
  {
    name: 'Giãn cơ vai ngực nằm',
    nameEn: 'Prone Shoulder Stretch',
    category: 'stretching',
    difficulty: 'easy',
    durationMinutes: 5,
    caloriesBurned: 22,
    imageUrl: null,
    description: 'Giãn cơ vai và ngực ở tư thế nằm, giải phóng căng thẳng.',
    steps: [
      { order: 1, instruction: 'Nằm sấp, giơ tay phải thẳng ra ngang vai.', durationSeconds: 5 },
      { order: 2, instruction: 'Lăn người sang trái dùng tay trái hỗ trợ.', durationSeconds: 10 },
      { order: 3, instruction: 'Cảm nhận giãn sâu ở vai và ngực phải.', durationSeconds: 30 },
      { order: 4, instruction: 'Giữ 30-45 giây rồi đổi bên.', durationSeconds: 45 },
    ],
    isActive: true,
  },
];

async function seed() {
  if (!process.env.MONGODB_URI) throw new Error('MONGODB_URI is not set');

  await mongoose.connect(process.env.MONGODB_URI);

  const existing = await Exercise.countDocuments({});

  if (existing >= 100) {
    console.log(`Đã có đủ bài tập, bỏ qua seed (count=${existing}).`);
    await mongoose.disconnect();
    return;
  }

  const result = await Exercise.insertMany(EXERCISES, { ordered: false });
  console.log(`Đã seed ${result.length} bài tập.`);

  await mongoose.disconnect();
}

seed().catch(err => {
  console.error(err);
  process.exit(1);
});
